### ISSUE TITLE
Does this work with mediastore?

### ISSUE THREAD

**Issue by colleenkhenry** [fsouza/s3-upload-proxy#17]
Hey. When I try using this for s3, it works fine. When I try mediastore, the objects get created in the bucket, but they are zero bytes in size. 

Is it working for others?

**Comment by fsouza** [comment]
Hey @colleenkhenry, thanks for reporting this. We're currently using it with s3 only. I'll investigate what's going on with the mediastore integration.

**Comment by colleenkhenry** [comment]
Thanks so much :D

**Comment by fsouza** [comment]
@colleenkhenry I was able to reproduce and fix this issue. It should work fine with version v0.7.3. Let me know if you see any issues!

**Comment by colleenkhenry** [comment]
You're my hero!
