### ISSUE TITLE
HTTP DELETE

### ISSUE THREAD

**Issue by colleenkhenry** [fsouza/s3-upload-proxy#18]
Hey! Thanks again for swiftly fixing the mediastore bug!

My http PUTs are working great to mediastore :). However, http DELETE seems to be ineffective. Is that something that I should expect to work, or, is that outside of the scope of what this shim does? 

Thank you again! This is really helpful!

**Comment by fsouza** [comment]
@colleenkhenry hey, currently DELETE isn't supported. Our current use case is specifically for live streaming and we never delete the video segments, but I'd love to hear more about your use case and if it makes sense we can implement support for it here.

I imagine that implementing delete should be simple. I can try to put something together over the weekend or early next week, or if you want to give it a shot, I'm happy to point you in the right direction and review the PR.

**Comment by colleenkhenry** [comment]
In fact I am working on live streaming as well! You can see one of my
projects here.. https://streamline.wtf

For me I just want to clean up the video segments as they are being written
by FFmpeg :).

**Comment by fsouza** [comment]
So yeah we can definitely implement this. I may be able to work on this tomorrow, but if not I can take a shot at it over the weekend or early next week. If you're willing to give it at shot, here's what's needed:

1. Extend the Uploader interface with a ``Delete`` method: https://github.com/fsouza/s3-upload-proxy/blob/905c5dc68e8330b7d6686ea333ac817c2e433d36/internal/uploader/uploader.go#L11-L13
1. Implement that method for [s3](https://github.com/fsouza/s3-upload-proxy/blob/905c5dc68e8330b7d6686ea333ac817c2e433d36/internal/uploader/s3/s3.go#L25) and [mediastore](https://github.com/fsouza/s3-upload-proxy/blob/905c5dc68e8330b7d6686ea333ac817c2e433d36/internal/uploader/mediastore/mediastore.go#L29) drivers
1. Update the http server to handle DELETE (the handler code is kinda too much right, so maybe we can do some refactoring :grin:): https://github.com/fsouza/s3-upload-proxy/blob/905c5dc68e8330b7d6686ea333ac817c2e433d36/main.go#L98-L124
