### ISSUE TITLE
api error InvalidSignatureException: Credential should be scoped to a valid region, not ''. "

### ISSUE THREAD

**Issue by CaitlinOCallaghan** [fsouza/s3-upload-proxy#241]
Hi, 

When I run s3-upload-proxy with MediaStore from the main branch or binary release, I receive the error:

`api error InvalidSignatureException: Credential should be scoped to a valid region, not ''. "`

If I revert to commit `793d1164921d6e42b4bec26686e76001995f218b`, I can properly upload to my container. 

I have tried setting environment variables from the command line and setting my `~.aws/config` file, but nothing has helped. Do you have any suggestions? 

My environment is:
- amd64 Ubuntu 18.04 VM
- go version go1.16.7 linux/amd64
- `~/.aws/config`
![image](https://user-images.githubusercontent.com/38890251/129589768-ce28f1f4-c155-4cce-91a0-ba2317f85454.png)
- `AWS_REGION=us-west-2`
- `AWS_DEFAULT_REGION=us-west-2`

I am really excited to use the `MEDIASTORE_CHUNKED_TRANSFER` feature, which is unavailable on the working commit. I hope we can get this working!  :)

**Comment by fsouza** [comment]
Hmm it looks like we're not detecting the region from the config file. I'll push a fix soon.

In the meantime, can you try setting the environment variable `AWS_REGION`?

**Comment by fsouza** [comment]
Actualyl nevermind I see that you have that environment variable set 🤔

**Comment by CaitlinOCallaghan** [comment]
The issue is specifically for doing a PUT to the container. The full message (with the personal info removed) is

`INFO[0000] listening on [::]:8080                       
ERRO[0004] failed to upload file bucket={my bucket name} contentType= error="operation error MediaStore Data: PutObject, https response error StatusCode: 403, RequestID: {ID}, api error InvalidSignatureException: Credential should be scoped to a valid region, not ''. " objectKey=live_video_init.m4s`

**Comment by CaitlinOCallaghan** [comment]
When you export your environment variable for the region, do you use single quotes, double quotes, or no quotes? I feel like I have tried all combinations with no success, but it's worth to double check.

**Comment by fsouza** [comment]
> When you export your environment variable for the region, do you use single quotes, double quotes, or no quotes? I feel like I have tried all combinations with no success, but it's worth to double check.

Hmm the shell should take either. I'll give it a shot later today.

**Comment by fsouza** [comment]
@CaitlinOCallaghan can you try with latest master? Here's my test:

```
env AWS_REGION=us-west-2 BUCKET_NAME=franciscotest UPLOAD_DRIVER=mediastore HTTP_PORT=8080 ./s3-upload-proxy
```

Then from another terminal:

```
％ curl -X POST --data-binary file1.ts localhost:8080/file/file1.ts
OK
```

I gave up on aws-sdk-go-v2, tired of being an early adopter of that lol

**Comment by CaitlinOCallaghan** [comment]
😍😍😍😍😍😍 THANK YOU SO MUCH!!!!!!!!!! IT WORKS!!!!!!!

**Comment by fsouza** [comment]
Nice! I'll close this, but feel free to open new issues if you run into other issues.
